name:                nray
version:             0.1.0.0
description:         Play with ray tracing
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              https://github.com/Nick-Chapman/nray.git

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
#- containers
#- extra
#- mtl
#- split

default-extensions:
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- NondecreasingIndentation
- NumericUnderscores
- RankNTypes
- ScopedTypeVariables

ghc-options:
- -Werror
- -Wall
- -Wno-name-shadowing
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  nray.exe:
    main:                Main.hs
    source-dirs:         src
